### PR TITLE
Reset translations when the number of replacements changes

### LINKED ISSUE #52: Warn when placeholder counts vary
We should warn when the number of placeholders in a localized string resource from a .resx file is greater than the number of placeholders in the string in the original string. Attempting to format using the localized string is likely to fail because there is no corresponding argument to `string.Format`, leading to an exception at run time.

This can happen if we already have a translation for a string such as `"{0} Alpha {1}"`, but it is later changed to have fewer placeholders, e.g. `"Alpha {0}"`. Until the next localization pass updates the .xlf files, the localized versions will still have two placeholders.

I imagine we would just have the MSBuild task check for this and log a warning. We may want to scope it to just .resx files.

### PR DESCRIPTION
**Pull request by tmeschter**
Fixes #52.

Reset translations when the number of replacements changes in the source text. If the number of replacement _increases_ then until the target string is updated to a new translation formatting it will likely produce misleading or just plain meaningless text.

If the number of replacements _decreases_ then the target string will refer to replacement items that no longer exist, leading to exceptions when formatting the target.

To avoid these problem just reset the target string to the source value when we detect that they require different numbers of replacement items. The tricky bit here is correctly identifying the placeholders so we can check their indices--here I've gone with a regex and attempted to document how it works.

### CODE REVIEW

File: src/XliffTasks/Model/XlfDocument.cs [hunk 1]
```diff
@@ -155,6 +155,26 @@ public bool Update(TranslatableDocument sourceDocument, string sourceDocumentId)
                     changed = true;
                 }
 
+                if (sourceDocument is ResxDocument)
```
[the remark this answers is not in the document]
Comment (nguerrera) [reply src/XliffTasks/Model/XlfDocument.cs]: This class shouldn't know what a resx is. If we want to limit it to only some formats, then we could have a virtual propery on TranslatableDocument. 

But I wonder if we can't just do this for all formats since:

1. Most documents are resx in practice, so I don't think perf helps.

2. I don't think we'd ever have a string in any translatable document with "{N}" where we expect translators to translate to anything other than "{N}".

File: src/XliffTasks/Model/ResxDocument.cs [hunk 2]
```diff
@@ -72,5 +74,46 @@ public override void RewriteRelativePathsToAbsolute(string sourceFullPath)
...
+        /// (\d+)
+        ///    The "index" component; one or more decimal digits. This is captured in a group
+        ///    to facilitate extracting the numeric value.
+        ///
+        /// (\,\-?\d+)?
+        ///    The optional "alignment" component. This is a comma, followed by an optional
+        ///    minus sign, followed by one or more decimal digits.
+        ///
+        /// (\:[^\}]+)?
+        ///    The optional "format string" componet. This is a colon, followed by one or more
```
Comment (nguerrera) [inline src/XliffTasks/Model/ResxDocument.cs]: typo: component

File: src/XliffTasks/Model/ResxDocument.cs [hunk 3]
```diff
@@ -72,5 +74,46 @@ public override void RewriteRelativePathsToAbsolute(string sourceFullPath)
...
+        ///    characters that aren't close curly braces.
+        ///
+        /// \}
+        ///    The close curly brace indicates the end of the placeholder.
+        /// </summary>
+        private static Regex s_placeHolderRegex = new Regex(@"\{(\d+)(\,\-?\d+)?(\:[^\}]+)?\}", RegexOptions.Compiled);
```
Comment (nguerrera) [inline src/XliffTasks/Model/ResxDocument.cs]: Now I have two problems. Sorry, couldn't resist. ;)

Man, this is hard to read. Thank you for the docs. I'm looking into another approach, but not sure if it'll be better yet.

File: src/XliffTasks/Model/ResxDocument.cs [hunk 4]
```diff
@@ -72,5 +74,46 @@ public override void RewriteRelativePathsToAbsolute(string sourceFullPath)
...
+
+        /// <summary>
+        /// Returns the number of replacement strings needed to properly format the given text.
+        /// </summary>
+        public static int GetReplacementCount(string text)
+        {
+            int placeHolderCount = 0;
```
Comment (nguerrera) [inline src/XliffTasks/Model/ResxDocument.cs]: nit: since "placeholder" is a word, it should be spelled without the capital H.

File: src/XliffTasks/Model/XlfDocument.cs [hunk 5]
```diff
@@ -155,6 +155,26 @@ public bool Update(TranslatableDocument sourceDocument, string sourceDocumentId)
...
+                    // target string is likely to produce misleading (or outright meaningless) text. In
+                    // either case we lose nothing by just reverting the string until it can be localized
+                    // again.
+                    var sourceReplacementCount = ResxDocument.GetReplacementCount(sourceElement.Value);
+                    var targetReplacementCount = ResxDocument.GetReplacementCount(targetElement.Value);
+
+                    if (targetReplacementCount != sourceReplacementCount)
+                    {
+                        targetElement.Value = sourceNode.Source;
+                        stateAttribute.Value = "new";
```
[the remark this answers is not in the document]
Comment (tmeschter) [reply src/XliffTasks/Model/XlfDocument.cs]: Bah. Right. I was even thinking that but just forgot to write the code.

File: src/XliffTasks/Model/ResxDocument.cs (hunk 3 above)
Comment (tmeschter) [reply src/XliffTasks/Model/ResxDocument.cs]: I thought about writing my own parser, and decided that "regex + copious comments" was shorter and easier to follow.

Comment (nguerrera) [reply src/XliffTasks/Model/ResxDocument.cs]: What about escaped `{{`?

(I would NOT recommend this, I found a HACK to use IFormatProvider + ICustomFormatter to count placeholders using string.Format: https://gist.github.com/nguerrera/dfd08d2ceaf38804cbcc5e60b1a48476 😆)

I'm looking at StringBuilder.AppendFormat now. Doesn't seem like the code would be very big if we stole it and replaced the appending with counting, but I'll give it a spin before endorsing that.

Comment (tmeschter) [reply src/XliffTasks/Model/ResxDocument.cs]: [Our docs on Escaping Braces](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting#escaping-braces) basically say "don't do that" so I've chosen not to worry about "{{" and "}}".

File: src/XliffTasks/Model/XlfDocument.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (tmeschter) [reply src/XliffTasks/Model/XlfDocument.cs]: Fixed.

File: src/XliffTasks/Model/XlfDocument.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (tmeschter) [reply src/XliffTasks/Model/XlfDocument.cs]: Fixed.

File: src/XliffTasks/Model/ResxDocument.cs (hunk 3 above)
Comment (nguerrera) [reply src/XliffTasks/Model/ResxDocument.cs]: StringBuilder.AppendFormat hacking is messier than I'd hoped. :(

File: src/XliffTasks/Model/ResxDocument.cs (hunk 2 above)
Comment (tmeschter) [reply src/XliffTasks/Model/ResxDocument.cs]: Fixed.

File: src/XliffTasks/Model/ResxDocument.cs (hunk 4 above)
Comment (tmeschter) [reply src/XliffTasks/Model/ResxDocument.cs]: Fixed.

File: src/XliffTasks/Model/XlfDocument.cs [hunk 6]
```diff
@@ -155,6 +155,25 @@ public bool Update(TranslatableDocument sourceDocument, string sourceDocumentId)
...
                 }
 
+                // If the source and target require different numbers of formatting items then reset
+                // the target string completely. This avoids problems when the source has been updated
+                // to remove formatting items--when formatting the target string we won't have as many
+                // replacement items as it calls for, leading to an exception.
+                // And if the source string is updated to use _more_ items then formatting with the
+                // target string is likely to produce misleading (or outright meaningless) text. In
+                // either case we lose nothing by just reverting the string until it can be localized
+                // again.
```
Comment (nguerrera) [inline src/XliffTasks/Model/XlfDocument.cs]: worth a comment as to why we don't limit ourselves to the case where the source has changed (if above): to catch a handback with wrong placeholder count.

File: src/XliffTasks.Tests/StringExtensionsTests.cs [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+            Assert.Equal(expected: 2, actual: replacementCount);
+        }
+
+        [Fact]
+        public void GetReplacementCount_MultipleIdenticalPlaceholders()
+        {
+            var text = "{2} {2}";
+            var replacementCount = text.GetReplacementCount();
+
+            Assert.Equal(expected: 3, actual: replacementCount);
```
Comment (nguerrera) [inline src/XliffTasks.Tests/StringExtensionsTests.cs]: Why do we expect 3 here?

Comment (tmeschter) [reply src/XliffTasks.Tests/StringExtensionsTests.cs]: What we really need to count is the number of items that need to get passed to `string.Format`, not the number of placeholders in the original text. A `{2}` placeholder implies that you need to pass at least three items to `string.Format`.

File: src/XliffTasks/Model/XlfDocument.cs (hunk 6 above)
Comment (nguerrera) [reply src/XliffTasks/Model/XlfDocument.cs]: nevermind, it is in the block. So this wouldn't catch the bad translation case. Because the source node in xlf would match the resx and we wouldn't get in here.

Comment (nguerrera) [reply src/XliffTasks/Model/XlfDocument.cs]: bleagh, wrong again, I think. Yes this method is too complex. Again, my fault.

File: src/XliffTasks.Tests/StringExtensionsTests.cs (hunk 7 above)
Comment (nguerrera) [reply src/XliffTasks.Tests/StringExtensionsTests.cs]: oh i see.

File: src/XliffTasks/Model/XlfDocument.cs (hunk 6 above)
Comment (tmeschter) [reply src/XliffTasks/Model/XlfDocument.cs]: Done.

File: src/XliffTasks.Tests/StringExtensionsTests.cs (hunk 7 above)
Comment (nguerrera) [reply src/XliffTasks.Tests/StringExtensionsTests.cs]: So {0} {1} {2} to be translated to {2} {2} {2} would pass? I think in terms of comparing translation to source, it would be fine to see that we have the same count..
